Code for Sequence Alignment, Sequence Similarity, and calculating the distance matrix from these

In [ ]:
def sequenceAlign(s1, s2, simMatrix=simDNA):
    numI = len(s1) + 1
    numJ = len(s2) + 1
    scoreMatrix = [[0] * numJ for x in range(numI)]
    routeMatrix = [[0] * numJ for x in range(numI)]
    for i in range(1, numI):
        routeMatrix[i][0] = 1
    for j in range(1, numJ):
        routeMatrix[0][j] = 2
    for i in range(1, numI):
        for j in range(1, numJ):
            penalty 1 = insert
            penalty 2 = insert
    if routeMatrix[i-1][j] == 1:
        penalty1 = extend

In [ ]:
def calcSeqSimilarity(s1, s2, simMatrix):
    numPlaces = min(len(s1), len(s2))
    totalScore = 0.0
    for i in range(numPlaces):
        residueA = s1[1]
        residueB = s2[i]
        totalScore += simMatrix[residueA][residueB]
    return totalScore

In [ ]:
def getDistanceMatrix(seqs, simMatrix):
    n = len(seqs)
    matrix = [[0.0] * n for x in range(n)]
    maxScores = [calcSeqSimilarity(x, x, simMatrix) for x in seqs]
    
    for i in range(n-1):
        s1 = seqs[i]
        
        for j in range(i+1, n):
            s2 = seqs[j]
            
            score, alignA, alignB = sequenceAlign(s1, s2, simMatrix)
            maxScore = max(maxScores[i], maxScores[j])
            dist = maxScore - score
            
            matrix[i][j] = dist
            matrix[j][i] = dist
            
    return matrix

In [1]:
import numpy as np
dMatrix_Values = ([[0, 0.5, 0.3, 0.6], [0.5, 0, 0.5, 0.5], 
                   [0.5, 0.5, 0, 0.4], [0.6, 0.5, 0.4, 0]])
dMatrix = np.reshape(dMatrix_Values, (4, 4))
print dMatrix

[[ 0.   0.5  0.3  0.6]
 [ 0.5  0.   0.5  0.5]
 [ 0.5  0.5  0.   0.4]
 [ 0.6  0.5  0.4  0. ]]
